# Generated by Django 6.0.5 on 2026-07-13 13:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello', models.SmallIntegerField(default=1)),
                ('data_nomina', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id_esame', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome_esame', models.CharField(max_length=50)),
                ('corso', models.CharField(max_length=100)),
                ('anno_corso', models.SmallIntegerField(default=1)),
                ('semestre', models.SmallIntegerField(default=0)),
                ('cfu', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Gruppo',
            fields=[
                ('id_gruppo', models.SmallAutoField(primary_key=True, serialize=False)),
                ('nome_gruppo', models.CharField(max_length=50)),
                ('link_chat', models.TextField(blank=True, null=True)),
                ('descrizione', models.TextField(blank=True, max_length=300, null=True)),
                ('max_partecipanti', models.SmallIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Materiale',
            fields=[
                ('nome_file', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=5)),
                ('file', models.FileField(default=None, null=True, upload_to='materiali/')),
                ('url', models.URLField(default=None, null=True)),
                ('data_caricamento', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('utente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=256)),
                ('ruolo', models.CharField(default='studente', max_length=20)),
                ('nome', models.CharField(max_length=50, null=True)),
                ('cognome', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dipartimento', models.CharField(max_length=128)),
                ('area_competenza', models.CharField(max_length=128)),
                ('laurea', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to='studymatch.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Studente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anno_corso', models.SmallIntegerField(default=0)),
                ('corso_laurea', models.CharField(max_length=100)),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studente_profile', to='studymatch.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Invio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data_invio', models.DateTimeField(auto_now_add=True)),
                ('letta', models.BooleanField(default=False)),
                ('mittente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invii_effettuati', to='studymatch.admin')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invii_ricevuti', to='studymatch.utente')),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to='studymatch.utente'),
        ),
        migrations.AddField(
            model_name='admin',
            name='notifica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studymatch.utente'),
        ),
        migrations.CreateModel(
            name='Gestione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_gruppo', to='studymatch.admin')),
                ('id_gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_admin', to='studymatch.gruppo')),
            ],
            options={
                'unique_together': {('admin', 'id_gruppo')},
            },
        ),
        migrations.CreateModel(
            name='Assegnazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateTimeField()),
                ('id_esame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esame_gruppo', to='studymatch.esame')),
                ('id_gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_esame', to='studymatch.gruppo')),
            ],
            options={
                'unique_together': {('id_esame', 'id_gruppo')},
            },
        ),
        migrations.CreateModel(
            name='Condivisione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_associato', to='studymatch.gruppo')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studymatch.materiale')),
            ],
            options={
                'unique_together': {('file', 'id_gruppo')},
            },
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_iscrizione', models.DateField(auto_now_add=True)),
                ('stato', models.BooleanField(default=False)),
                ('id_gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_utente', to='studymatch.gruppo')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utente_gruppo', to='studymatch.studente')),
            ],
            options={
                'unique_together': {('studente', 'id_gruppo')},
            },
        ),
        migrations.CreateModel(
            name='Svolgimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_svolgimento', models.DateField(auto_now_add=True)),
                ('id_esame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esame_svolto', to='studymatch.esame')),
                ('studente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studente_successo', to='studymatch.studente')),
            ],
            options={
                'unique_together': {('studente', 'id_esame')},
            },
        ),
        migrations.CreateModel(
            name='Supporto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punteggio', models.IntegerField(blank=True, null=True)),
                ('id_gruppo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gruppo_tutor', to='studymatch.gruppo')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_gruppo', to='studymatch.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'id_gruppo')},
            },
        ),
    ]
